---
apiVersion: consul.hashicorp.com/v1alpha1
kind: ServiceDefaults
metadata:
  name: echo-1
  namespace: consul
spec:
  protocol: http
---
apiVersion: v1
kind: Service
metadata:
  labels:
    app: echo-1
  name: echo-1
  namespace: consul
spec:
  ports:
  - port: 8080
    name: high
    protocol: TCP
    targetPort: 8443
  selector:
    app: echo-1
---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: echo-1
  namespace: consul
automountServiceAccountToken: true
---
apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: echo-1
  name: echo-1
  namespace: consul
spec:
  replicas: 1
  selector:
    matchLabels:
      app: echo-1
  template:
    metadata:
      labels:
        app: echo-1
      annotations:
        'consul.hashicorp.com/connect-inject': 'true'
    spec:
      serviceAccountName: echo-1
      containers:
      - image: k8s.gcr.io/echoserver:1.4
        name: echo-1
        env:
        - name: SERVICE_NAME
          value: echo-1
        - name: POD_NAME
          valueFrom:
            fieldRef:
              fieldPath: metadata.name
        - name: NAMESPACE
          valueFrom:
            fieldRef:
              fieldPath: metadata.namespace
        ports:
        - containerPort: 8080
